### PR TITLE
fix typo introduced with extra_bind_settings

### PR DESCRIPTION
**Pull request by dominicmarmont**
I was getting the following error with the latest build:

`2015-10-07T11:34:05.992770620Z ERROR:root:'Haproxy' object has no attribute 'port_num'`

traced it back to a typo introduced with https://github.com/tutumcloud/haproxy/commit/4a01ce3bd724a6166a82be1d877564cbc61e57d3

### CODE REVIEW

**Comment by tifayuki** [comment]
Thank you
